# Generated by Django 3.0.7 on 2020-06-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200629_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping1', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping2', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping3', to='orders.Topping'),
        ),
    ]
